act_Hoteles/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.Persona.views import home
# from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', home),
    path('habitaciones/', include('apps.Habitacion.urls', namespace="habitaciones")),
    path('agencia_de_viajes/', include('apps.Agencia_de_viaje.urls', namespace="agencia_de_viajes")),
    path('personas/', include('apps.Persona.urls', namespace="personas")),
    path('categorias/', include('apps.Categoria.urls', namespace="categorias")),
    path('reservas/', include('apps.Reserva.urls', namespace="reservas")),
    path('hoteles/', include('apps.Hotel.urls', namespace="hoteles"))
]

apps/Reserva/urls.py
from django.urls import path, include

from apps.Reserva.views import index, reservaCreate, reservaEdit, reservaEliminar


app_name = "Reservas"
urlpatterns = [
    path('', index, name ='index'), 
    path('nuevo/', reservaCreate, name='reservaCreate'), 
    path('actualizar/<int:id_reserva>/', reservaEdit, name='reservaEdit'), 
    path('eliminar/<int:id_reserva>/', reservaEliminar, name='reservaEliminar'), 
]

apps/Reserva/models.py
from django.db import models
from apps.Hotel.models import Hotel
from apps.Persona.models import Persona
from apps.Agencia_de_viaje.models import Agencia_de_viaje

# Create your models here.



class Reserva(models.Model):

    
    
    Fecha_ingreso    = models.DateField()
    Fecha_salida    = models.DateField()
    Hora_ingreso    = models.CharField(max_length=30)
    Hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    Persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    Agencia_de_viaje = models.ForeignKey(Agencia_de_viaje, on_delete=models.CASCADE)

    def __str__(self):
        return self.Hora_ingreso

    class Meta:
        verbose_name = "Reserva"
        verbose_name_plural = "Reservas"    

apps/Reserva/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from apps.Reserva.models import Reserva
from apps.Reserva.form import ReservaForm




# Create your views here.

def home(request):
    
    return render(request, 'base/base.html')

def index(request):
    reserva = Reserva.objects.all().order_by('-id')
    context = {'reservas': reserva}
    return render(request, 'Reserva/index.html', context)
    # return render(request,'Agencia_de_viaje/index.html')

    # /////////////////////////////////////Codigo de Crear - mostrar///////////////////////////

def reservaCreate(request):
    if (request.method == 'POST'):
        form = ReservaForm(request.POST)
        if  form.is_valid():
            form.save()

        
        return redirect('Reservas:index')

    else:
        form = ReservaForm()
        return render(request, 'Reserva/formReserva.html', {'form': form})


#  /////////////////////////////////////Codigo de actualizar///////////////////////////

def reservaEdit(request,id_reserva):

    reserva = Reserva.objects.get(pk=id_reserva)

    if request.method == 'GET':
        form = ReservaForm(instance=reserva)
    else:
        form = ReservaForm(request.POST, instance=reserva)
        if form.is_valid():
            form.save()
        return redirect('Reservas:index')
    
    return render(request, 'Reserva/formReserva.html', {'form': form})

#  /////////////////////////////////////Codigo de Eliminar///////////////////////////

def reservaEliminar(request,id_reserva):

    reserva = Reserva.objects.get(pk=id_reserva)

    if request.method == 'POST':
        reserva.delete()
        return redirect('reservas:index')

    return render(request, 'Reserva/reservaEliminar.html', {'Reserva': reserva})
    

    

templates/Reserva/formReserva.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post" >


    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary" type="submit">
        Guardar
    </button>


  </form>
{% endblock %}

templates/Reserva/index.html
{% extends 'base/base.html' %}


{% block content %}
  <h3> Listado De Reservas </h3>
  
  <h1 class="pull-right"> </h1>
  <a href="{% url 'Reservas:reservaCreate' %}" class="btn btn-success pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
<!-- ////////////////////////////////////////////////////////////// -->


  <table class="table  table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Fecha_ingreso</th>
        <th scope="col">Fecha_salida</th>
        <th scope="col">Hora_ingreso</th>
        <th scope="col">Hotel</th>
        <th scope="col">Persona</th>
        <th scope="col">Agencia_de_viaje</th>
      </tr>
    </thead>
    <tbody>


      {% if reservas %}

        {% for reserva in reservas %}
            <tr>
                
                <td>{{ reserva.id}}</td>
                <td>{{ reserva.Fecha_ingreso}}</td>
                <td>{{ reserva.Fecha_salida}}</td>
                <td>{{ reserva.Hora_ingreso}}</td>
                <td>{{ reserva.Hotel}}</td>
                <td>{{ reserva.Persona}}</td>
                <td>{{ reserva.Agencia_de_viaje}}</td>

                <td>
                  <a class="btn btn-warning " href="{% url 'Reservas:reservaEdit' reserva.id %}" >
                    <i class="fas fa-user-edit"></i>
                  </a>
  
                  
                  <a class="btn btn-danger " href="{% url 'Reservas:reservaEliminar' reserva.id %}" >
                    <i class="fas fa-user-times"></i>
                  </a>
                </td>
            </tr>
      {% endfor %}

      {% else %}

      <h3> No existe Registros De Reservas </h3>
   {% endif %}
      
     
    </tbody>
  </table>
  
{% endblock %}

templates/Reserva/inicio.html
{% extends 'base/base.html' %}


{% block content %}
  <h3> mostrando  Tabla Reserva</h3>
{% endblock %}

templates/Reserva/reservaEliminar.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post">
      {% csrf_token %}
      <h4>¿Estas Seguro De Eliminar La Informacion ?</h4>
      <button class="btn btn-danger" type="submit">Claro, Hazlo</button>
      <a class="btn btn-primary" href="{% url 'Reservas:index' %}">Cancelar</a>

  </form>

{% endblock %}