act_Hoteles/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.Persona.views import home
# from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', home),
    path('habitaciones/', include('apps.Habitacion.urls', namespace="habitaciones")),
    path('agencia_de_viajes/', include('apps.Agencia_de_viaje.urls', namespace="agencia_de_viajes")),
    path('personas/', include('apps.Persona.urls', namespace="personas")),
    path('categorias/', include('apps.Categoria.urls', namespace="categorias")),
    path('reservas/', include('apps.Reserva.urls', namespace="reservas")),
    path('hoteles/', include('apps.Hotel.urls', namespace="hoteles"))
]

apps/Agencia_de_viaje/urls.py
from django.urls import path, include

from apps.Agencia_de_viaje.views import index, agencia_de_viajeCreate, agencia_de_viajeEdit, agencia_de_viajeEliminar


app_name = "Agencia_de_viajes"
urlpatterns = [
    path('', index, name ='index'), 
    path('nuevo/', agencia_de_viajeCreate, name='agencia_de_viajeCreate'), 
    path('actualizar/<int:id_agencia_de_viaje>/', agencia_de_viajeEdit, name='agencia_de_viajeEdit'), 
    path('eliminar/<int:id_agencia_de_viaje>/', agencia_de_viajeEliminar, name='agencia_de_viajeEliminar'), 
]

apps/Agencia_de_viaje/models.py
from django.db import models

# Create your models here.


class Agencia_de_viaje(models.Model):

    
    Nombre    = models.CharField(max_length=100)
    Direccion    = models.CharField(max_length=45)
    Telefono    = models.CharField(max_length=15)
    Ciudad    = models.CharField(max_length=50)

    def __str__(self):
        return self.Nombre



    class Meta:
        verbose_name = "Agencia_de_viaje"
        verbose_name_plural = "Agencia_de_viajes"

apps/Agencia_de_viaje/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from apps.Agencia_de_viaje.models import Agencia_de_viaje
from apps.Agencia_de_viaje.form import Agencia_de_viajeForm




# Create your views here.

def home(request):
    
    return render(request, 'base/base.html')

def index(request):
    agencia_de_viaje = Agencia_de_viaje.objects.all().order_by('-id')
    context = {'agencia_de_viajes': agencia_de_viaje}
    return render(request, 'Agencia_de_viaje/index.html', context)
    # return render(request,'Agencia_de_viaje/index.html')


    # /////////////////////////////////////Codigo de Crear - mostrar///////////////////////////

def agencia_de_viajeCreate(request):
    if (request.method == 'POST'):
        form = Agencia_de_viajeForm(request.POST)
        if  form.is_valid():
            form.save()

        
        return redirect('Agencia_de_viajes:index')

    else:
        form = Agencia_de_viajeForm()
        return render(request, 'Agencia_de_viaje/formAgencia_de_viaje.html', {'form': form})


#  /////////////////////////////////////Codigo de actualizar///////////////////////////

def agencia_de_viajeEdit(request,id_agencia_de_viaje):

    agencia_de_viaje = Agencia_de_viaje.objects.get(pk=id_agencia_de_viaje)

    if request.method == 'GET':
        form = Agencia_de_viajeForm(instance=agencia_de_viaje)
    else:
        form = Agencia_de_viajeForm(request.POST, instance=agencia_de_viaje)
        if form.is_valid():
            form.save()
        return redirect('Agencia_de_viajes:index')
    
    return render(request, 'Agencia_de_viaje/formAgencia_de_viaje.html', {'form': form})

#  /////////////////////////////////////Codigo de Eliminar///////////////////////////

def agencia_de_viajeEliminar(request,id_agencia_de_viaje):

    agencia_de_viaje = Agencia_de_viaje.objects.get(pk=id_agencia_de_viaje)

    if request.method == 'POST':
        agencia_de_viaje.delete()
        return redirect('agencia_de_viajes:index')

    return render(request, 'Agencia_de_viaje/agencia_de_viajeEliminar.html', {'Agencia_de_viaje': agencia_de_viaje})
    

    

templates/Agencia_de_viaje/agencia_de_viajeEliminar.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post">
      {% csrf_token %}
      <h4>¿Estas Seguro De Eliminar La Informacion ?</h4>
      <button class="btn btn-danger" type="submit">Claro, Hazlo</button>
      <a class="btn btn-primary" href="{% url 'Agencia_de_viajes:index' %}">Cancelar</a>

  </form>

{% endblock %}

templates/Agencia_de_viaje/formAgencia_de_viaje.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post" >


    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary" type="submit">
        Guardar
    </button>


  </form>
{% endblock %}

templates/Agencia_de_viaje/index.html
{% extends 'base/base.html' %}


{% block content %}
  <h3> Listado De Agencias Viajeras </h3>
  
  <h1 class="pull-right"> </h1>
  <a href="{% url 'Agencia_de_viajes:agencia_de_viajeCreate' %}" class="btn btn-success pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
<!-- ////////////////////////////////////////////////////////////// -->


  <table class="table  table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Direccion</th>
        <th scope="col">Telefono</th>
        <th scope="col">Ciudad</th>
      </tr>
    </thead>
    <tbody>


      {% if agencia_de_viajes %}

        {% for agencia_de_viaje in agencia_de_viajes %}
            <tr>
                
                <td>{{ agencia_de_viaje.id}}</td>
                <td>{{ agencia_de_viaje.Nombre}}</td>
                <td>{{ agencia_de_viaje.Direccion}}</td>
                <td>{{ agencia_de_viaje.Telefono}}</td>
                <td>{{ agencia_de_viaje.Ciudad}}</td>

                <td>
                  <a class="btn btn-warning " href="{% url 'Agencia_de_viajes:agencia_de_viajeEdit' agencia_de_viaje.id %}" >
                    <i class="fas fa-user-edit"></i>
                  </a>
  
                  
                  <a class="btn btn-danger " href="{% url 'Agencia_de_viajes:agencia_de_viajeEliminar' agencia_de_viaje.id %}" >
                    <i class="fas fa-user-times"></i>
                  </a>
                </td>
            </tr>
      {% endfor %}

      {% else %}

      <h3> No existe Registros De Agencias </h3>
   {% endif %}
      
     
    </tbody>
  </table>
  
{% endblock %}

templates/Agencia_de_viaje/inicio.html
{% extends 'base/base.html' %}


{% block content %}
  <h3> mostrando  Tabla Agencias</h3>
{% endblock %} 