act_Hoteles/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.Persona.views import home
# from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', home),
    path('habitaciones/', include('apps.Habitacion.urls', namespace="habitaciones")),
    path('agencia_de_viajes/', include('apps.Agencia_de_viaje.urls', namespace="agencia_de_viajes")),
    path('personas/', include('apps.Persona.urls', namespace="personas")),
    path('categorias/', include('apps.Categoria.urls', namespace="categorias")),
    path('reservas/', include('apps.Reserva.urls', namespace="reservas")),
    path('hoteles/', include('apps.Hotel.urls', namespace="hoteles"))
]

apps/Categoria/urls.py
from django.urls import path, include

from apps.Categoria.views import index, categoriaCreate, categoriaEdit, categoriaEliminar

app_name = "Categorias"
urlpatterns = [
    path('', index, name ='index'), 
    path('nuevo/', categoriaCreate, name='categoriaCreate'), 
    path('actualizar/<int:id_categoria>/', categoriaEdit, name='categoriaEdit'), 
    path('eliminar/<int:id_categoria>/', categoriaEliminar, name='categoriaEliminar'), 
]

apps/Categoria/models.py
from django.db import models

class Categoria(models.Model):

    Iva = models.CharField(max_length=20)
    Descripcion   = models.CharField(max_length=80)


    def __str__(self):
        return self.Descripcion



    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"    

apps/Categoria/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from apps.Categoria.models import Categoria
from apps.Categoria.form import CategoriaForm




# Create your views here.

def home(request):
    
    return render(request, 'base/base.html')

def index(request):
    categoria = Categoria.objects.all().order_by('-id')
    context = {'categorias': categoria}
    return render(request, 'Categoria/index.html', context)
    # return render(request,'Agencia_de_viaje/index.html')


    # /////////////////////////////////////Codigo de Crear - mostrar///////////////////////////

def categoriaCreate(request):
    if (request.method == 'POST'):
        form = CategoriaForm(request.POST)
        if  form.is_valid():
            form.save()

        
        return redirect('Categorias:index')

    else:
        form = CategoriaForm()
        return render(request, 'Categoria/formCategoria.html', {'form': form})


#  /////////////////////////////////////Codigo de actualizar///////////////////////////

def categoriaEdit(request,id_categoria):

    categoria = Categoria.objects.get(pk=id_categoria)

    if request.method == 'GET':
        form = CategoriaForm(instance=categoria)
    else:
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
        return redirect('Categorias:index')
    
    return render(request, 'Categoria/formCategoria.html', {'form': form})

#  /////////////////////////////////////Codigo de Eliminar///////////////////////////

def categoriaEliminar(request,id_categoria):

    categoria = Categoria.objects.get(pk=id_categoria)

    if request.method == 'POST':
        categoria.delete()
        return redirect('categorias:index')

    return render(request, 'Categoria/categoriaEliminar.html', {'Categoria': categoria})
    

    

templates/Categoria/categoriaEliminar.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post">
      {% csrf_token %}
      <h4>¿Estas Seguro De Eliminar La Informacion?</h4>
      <button class="btn btn-danger" type="submit">Claro, Hazlo</button>
      <a class="btn btn-primary" href="{% url 'Categorias:index' %}">Cancelar</a>

  </form>

{% endblock %}

templates/Categoria/formCategoria.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post" >


    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary" type="submit">
        Guardar
    </button>


  </form>
{% endblock %}

templates/Categoria/index.html
{% extends 'base/base.html' %}

<!-- //////////////////////////////////esto es nuevo /////////////////////////// -->
{% block content %}
  <h3> Listado De Categorias </h3>

  <h1 class="pull-right"> </h1>
  <a href="{% url 'Categorias:categoriaCreate' %}" class="btn btn-success pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
<!-- ////////////////////////////////////////////////////////////// -->

  <table class="table  table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Iva</th>
        <th scope="col">Descripcion</th>
      </tr>
    </thead>
    <tbody>
<!-- ////////////////////////////////////////////////////////////// -->
      {% if categorias %}

        {% for categoria in categorias %}
            <tr>
                
                <td>{{ categoria.id}}</td>
                <td>{{ categoria.Iva}}</td>
                <td>{{ categoria.Descripcion}}</td>
                <td>
                  <a class="btn btn-warning " href="{% url 'Categorias:categoriaEdit' categoria.id %}" >
                    <i class="fas fa-user-edit"></i>
                  </a>
  
                  
                  <a class="btn btn-danger " href="{% url 'Categorias:categoriaEliminar' categoria.id %}" >
                    <i class="fas fa-user-times"></i>
                  </a>
                </td>
            </tr>
     {% endfor %}

     {% else %}

     <h3> No existe Registros en Categorias </h3>
   {% endif %}
<!-- ////////////////////////////////////////////////////////////// -->
    </tbody>
  </table>
  
{% endblock %}

templates/Categoria/inicio.html
{% extends 'base/base.html' %}


{% block content %}
  <h3> mostrando  Tabla Categorias</h3>
{% endblock %}