act_Hoteles/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.Persona.views import home
# from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', home),
    path('habitaciones/', include('apps.Habitacion.urls', namespace="habitaciones")),
    path('agencia_de_viajes/', include('apps.Agencia_de_viaje.urls', namespace="agencia_de_viajes")),
    path('personas/', include('apps.Persona.urls', namespace="personas")),
    path('categorias/', include('apps.Categoria.urls', namespace="categorias")),
    path('reservas/', include('apps.Reserva.urls', namespace="reservas")),
    path('hoteles/', include('apps.Hotel.urls', namespace="hoteles"))
]

apps/Persona/urls.py
from django.urls import path, include

from apps.Persona.views import index, personaCreate, personaEdit, personaEliminar

app_name = "Personas"
urlpatterns = [
    path('', index, name ='index'), 
    path('nuevo/', personaCreate, name='personaCreate'), 
    path('actualizar/<int:id_persona>/', personaEdit, name='personaEdit'), 
    path('eliminar/<int:id_persona>/', personaEliminar, name='personaEliminar'), 
]

apps/Persona/models.py
from django.db import models

# Create your models here.


class Persona(models.Model):

    
    Nombre    = models.CharField(max_length=100)
    Apellido   = models.CharField(max_length=50)
    Direccion    = models.CharField(max_length=45)
    Telefono    = models.CharField(max_length=15)

    def __str__(self):
        return self.Nombre



    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"

apps/Persona/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from apps.Persona.models import Persona
from apps.Persona.form import PersonaForm

# Create your views here.

def home(request):
    
    return render(request, 'base/base.html')


def index(request):
    persona = Persona.objects.all().order_by('-id')
    context = {'personas': persona}
    return render(request, 'persona/index.html', context)
    # return render(request,'persona/index.html')


# /////////////////////////////////////Codigo de Crear - mostrar///////////////////////////

def personaCreate(request):
    if (request.method == 'POST'):
        form = PersonaForm(request.POST)
        if  form.is_valid():
            form.save()

        
        return redirect('personas:index')

    else:
        form = PersonaForm()
        return render(request, 'persona/formPersona.html', {'form': form})


#  /////////////////////////////////////Codigo de actualizar///////////////////////////

def personaEdit(request,id_persona):

    persona = Persona.objects.get(pk=id_persona)

    if request.method == 'GET':
        form = PersonaForm(instance=persona)
    else:
        form = PersonaForm(request.POST, instance=persona)
        if form.is_valid():
            form.save()
        return redirect('personas:index')
    
    return render(request, 'persona/formPersona.html', {'form': form})

#  /////////////////////////////////////Codigo de Eliminar///////////////////////////

def personaEliminar(request,id_persona):

    persona = Persona.objects.get(pk=id_persona)

    if request.method == 'POST':
        persona.delete()
        return redirect('personas:index')

    return render(request, 'persona/personaEliminar.html', {'persona': persona})
    






  

templates/persona/formPersona.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post" >


    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary" type="submit">
        Guardar
    </button>


  </form>
{% endblock %}

templates/persona/index.html
{% extends 'base/base.html' %}

<!-- //////////////////////////////////esto es nuevo /////////////////////////// -->
{% block content %}
  <h3> Listado De Personas </h3>

  <h1 class="pull-right"> </h1>
  <a href="{% url 'Personas:personaCreate' %}" class="btn btn-success pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
<!-- ////////////////////////////////////////////////////////////// -->

  <table class="table  table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Direccion</th>
        <th scope="col">Telefono</th>
      </tr>
    </thead>
    <tbody>
<!-- ////////////////////////////////////////////////////////////// -->
      {% if personas %}

        {% for persona in personas %}
            <tr>
                
                <td>{{ persona.id}}</td>
                <td>{{ persona.Nombre}}</td>
                <td>{{ persona.Apellido}}</td>
                <td>{{ persona.Direccion}}</td>
                <td>{{ persona.Telefono}}</td>
                <td>
                  <a class="btn btn-warning " href="{% url 'Personas:personaEdit' persona.id %}" >
                    <i class="fas fa-user-edit"></i>
                  </a>
  
                  
                  <a class="btn btn-danger " href="{% url 'Personas:personaEliminar' persona.id %}" >
                    <i class="fas fa-user-times"></i>
                  </a>
                </td>
            </tr>
     {% endfor %}

     {% else %}

     <h3> No existe Registros en Personas </h3>
   {% endif %}
<!-- ////////////////////////////////////////////////////////////// -->
    </tbody>
  </table>
  
{% endblock %}

templates/persona/inicio.html
{% extends 'base/base.html' %}


{% block content %}
  <h3> mostrando  Tabla Personas </h3>
{% endblock %}

templates/persona/personaEliminar.html
{% extends 'base/base.html' %}


{% block content %}
  <form method="post">
      {% csrf_token %}
      <h4>¿Estas Seguro De Eliminar La Informacion de {{ persona.Nombre }} ?</h4>
      <button class="btn btn-danger" type="submit">Claro, Hazlo</button>
      <a class="btn btn-primary" href="{% url 'Personas:index' %}">Cancelar</a>

  </form>

{% endblock %}